# See example.yaml if unfamiliar with how to use.

common:
  args:
    storage: mcap
    max-bag-duration: 120
    # storage-config-file: /home/tartandriver/tartandriver_ws/src/core/bag_recorder_pid/config/mcap_qos.yaml
  routines:
    pre_logger:
      - type: routines.example_routine.pre_logger
    post_logger:
      - type: routines.example_routine.post_logger
      - type: routines.freq.bag_freq

bags:
  tartandriver:
    topics:
      - $ALL_TOPICS
      # - $ACTUATION_TOPICS
      # - $NOVATEL_TOPICS
      # - $MULTISENSE_TOPICS
      # - $VELODYNE_TOPICS
      # - $CORE_TOPICS
      # - $SENSOR_TOPICS
      # - $THERMAL_TOPICS
      # - $AUTO_TOPICS