bags:
  tartandriver:
    storage_config: mcap_qos.yaml
    args:
      -s: mcap
      -d: 120
    hooks:
      pre_logger:
        - bag_record_pid.example_routine
      post_logger:
        - bag_record_pid.example_routine
    topics:
      - $ALL_TOPICS
      # - $ACTUATION_TOPICS
      # - $NOVATEL_TOPICS
      # - $MULTISENSE_TOPICS
      # - $VELODYNE_TOPICS
      # - $CORE_TOPICS
      # - $SENSOR_TOPICS
      # - $THERMAL_TOPICS
      # - $AUTO_TOPICS

