# Any line that does not start with a / will be automatically prefixed using the 
# namespace of the bag_record_pid node.
# mcap_qos is the filename of the MCAP QoS profile. The actual directory will be prefixed by the
# bag_record_pid node via a user specified argument. All MCAP QoS files must be in the same directory.
# The -o or --output argument should not be specified here.
# The -s mcap option will be added automatically.
sections:
  undistorted_images_all_cameras:
    mcap_qos: mcap_qos.yaml
    args: 
      - -b
      - 40000000000 # ~40GB
      - --max-cache-size 
      - 2147483648 # 2GB
      # - --qos-profile-overrides-path
      # - /root/ros2_ws_new/src/bag_recorder_pid/config/qos_overrides.yaml
    topics:
      - /diagnostics
      - /parameter_events
      - /rosout
      - /tf
      - /tf_static
      - /thermal_left/camera_info
      - /thermal_left/ffc_status
      # - /thermal_left/image
      # - /thermal_left/image_processed
      - /thermal_left/image_rect
      - /thermal_right/camera_info
      - /thermal_right/ffc_status
      # - /thermal_right/image
      # - /thermal_right/image_processed
      - /thermal_right/image_rect
      - /zed/joint_states
      - /zed/robot_description
      - /zed/zed_node/imu/data
      - /zed/zed_node/imu/data_raw
      - /zed/zed_node/left/camera_info
      - /zed/zed_node/left/image_rect_color
      - /zed/zed_node/left_cam_imu_transform
      # - /zed/zed_node/left_raw/camera_info
      # - /zed/zed_node/left_raw/image_raw_color
      - /zed/zed_node/right/camera_info
      - /zed/zed_node/right/image_rect_color
      # - /zed/zed_node/right_raw/camera_info
      # - /zed/zed_node/right_raw/image_raw_color
      - /zed/zed_node/status/health
      - /zed/zed_node/status/heartbeat
      - /zed/zed_node/temperature/imu
      - /health/thermal_left/frequency
      - /health/thermal_left/status
      - /health/thermal_right/frequency
      - /health/thermal_right/status
      - /health/zed/frequency
      - /health/zed/status

#skipped topics 
# - /zed/zed_node/right_raw_gray/camera_info
# - /zed/zed_node/right_raw_gray/image_raw_gray
# - /zed/zed_node/stereo/image_rect_color
# - /zed/zed_node/stereo_raw/image_raw_color
# - /zed/zed_node/right_gray/camera_info
# - /zed/zed_node/right_gray/image_rect_gray
# - /zed/zed_node/left_raw_gray/camera_info
# - /zed/zed_node/left_raw_gray/image_raw_gray
# - /zed/zed_node/rgb/camera_info
# - /zed/zed_node/rgb/image_rect_color
# - /zed/zed_node/rgb_gray/camera_info
# - /zed/zed_node/rgb_gray/image_rect_gray
# - /zed/zed_node/rgb_raw/camera_info
# - /zed/zed_node/rgb_raw/image_raw_color
# - /zed/zed_node/rgb_raw_gray/camera_info
# - /zed/zed_node/rgb_raw_gray/image_raw_gray
# - /zed/zed_node/left_gray/camera_info
# - /zed/zed_node/left_gray/image_rect_gray